### ISSUE TITLE
Linked mentions flicker while typing in file

### ISSUE THREAD

**Issue by sersorrel** [jensmtg/influx#59] opened 2023-01-30 09:45 UTC
**Describe the bug**
While I'm typing in a file, the influx linked mentions section at the bottom occasionally flickers out of existence for a moment.

**To Reproduce**
1. Install Influx
2. In a note where "Linked mentions (influx)" appears, type some text (seems to happen most often when starting a new paragraph, but it's not super consistent)
3. Notice that the "Linked mentions (influx)" section occasionally flashes out of existence for a second

**Expected behavior**
The linked mentions section should not flicker in and out of existence. (Obviously if there are changes then they need to appear, but ideally they would just appear immediately without the few hundred milliseconds of the section not existing at all, and if the changes are to the document the links appear in (as opposed to documents that link to it), it seems like the section shouldn't need updating at all)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.3
 - Obsidian version: 1.1.9
 - Influx version: 2.0.7

**Additional context**
Turning "live update" off doesn't seem to affect anything about the flickering.

**Comment by jensmtg** [comment] 2023-02-03 07:27
Duplicate of https://github.com/jensmtg/influx/issues/40.
Should be solved now, as described in that thread.

**Closed by jensmtg** 2023-02-03 07:27 UTC
Labels: bug
