### ISSUE TITLE
Plugin causes glitch deleting text

### ISSUE THREAD

**Issue by oldjove** [jensmtg/influx#29] opened 2022-10-19 14:29 UTC
Just trying out the plugin, which seems really great. However, as soon as I enabled it, I began experiencing a strange glitch when using the backspace or delete keys to delete text in a note in which letters are sometimes undeleted. It seems quite erratic -- not sure what the pattern it. Seems it only happens when I hit the key rapidly. If I slowly hit the delete or backspace, everything works as it should. Disabling the plugin removes the problem. I'm using Obsidian 1.0 on Windows 10.

**Comment by jensmtg** [comment] 2022-10-19 15:39
This looks like a duplicate of #8, at least in that the underlaying problem seems to relate to the way codemirror handles widgets. 
It's out of my hands to handle this directly, but I guess there could be made a workaround that temporary disables influx when editing a note, and reinserts it after editing is done. 
I'll consider looking into this at some point. For now, I think the best workaround may be to disable live-preview of the influx component.

**Comment by oldjove** [comment] 2022-10-20 10:43
I see. I'm note sure if you meant I should turn off Influx's "live update" setting. I will try working with this and see if it helps any. Thanks.

**Comment by jensmtg** [comment] 2022-10-24 07:53
Duplicate of #40

**Closed by jensmtg** 2022-10-24 07:53 UTC
Labels: enhancement, might fix
